const WORD_LISTS = {
    en: {
        name: 'English',
        easy: [
            'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'it',
            'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at', 'this',
            'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she', 'or',
            'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what', 'so',
            'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me', 'when',
            'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know', 'take', 'people',
            'into', 'year', 'your', 'good', 'some', 'could', 'them', 'see', 'other', 'than',
            'then', 'now', 'look', 'only', 'come', 'its', 'over', 'think', 'also', 'back',
            'after', 'use', 'two', 'how', 'our', 'work', 'first', 'well', 'way', 'even',
            'new', 'want', 'because', 'any', 'these', 'give', 'day', 'most', 'us', 'great'
        ],
        normal: [
            'ability', 'absorb', 'abstract', 'academy', 'accelerate', 'accept', 'access', 'accomplish',
            'account', 'accumulate', 'accurate', 'achieve', 'acknowledge', 'acquire', 'activate',
            'adapt', 'address', 'adequate', 'adjust', 'administration', 'adopt', 'advance',
            'adventure', 'analysis', 'ancient', 'announce', 'annual', 'anxiety', 'apparent',
            'appeal', 'application', 'approach', 'appropriate', 'approve', 'architecture',
            'archive', 'arrange', 'articulate', 'artificial', 'assemble', 'assessment',
            'assign', 'assist', 'associate', 'assume', 'atmosphere', 'attach', 'attempt',
            'attend', 'attract', 'authority', 'automatic', 'available', 'average', 'avoid',
            'balance', 'barrier', 'battery', 'battle', 'beautiful', 'become', 'beginning',
            'behavior', 'believe', 'belong', 'benefit', 'beyond', 'billion', 'biology',
            'blank', 'bother', 'boundary', 'brainstorm', 'branch', 'brand', 'brave', 'breath',
            'bridge', 'brief', 'brilliant', 'broad', 'budget', 'build', 'burden', 'burn',
            'business', 'calendar', 'campaign', 'capable', 'capacity', 'capture', 'career',
            'careful', 'catalog', 'category', 'celebrate', 'ceremony', 'challenge', 'champion',
            'channel', 'chapter', 'character', 'charge', 'charity', 'charter', 'chemical',
            'choose', 'chunk', 'circuit', 'circular', 'circumstance', 'citizen', 'civil',
            'classic', 'classroom', 'client', 'climate', 'clinic', 'closure', 'clothing',
            'cluster', 'coach', 'coastal', 'code', 'cognitive', 'collapse', 'colleague',
            'collect', 'college', 'colonial', 'column', 'combat', 'combine', 'comedy',
            'comfort', 'command', 'comment', 'commerce', 'commission', 'commit', 'commodity',
            'common', 'communicate', 'community', 'company', 'compare', 'compete', 'compile',
            'complex', 'component', 'compose', 'comprehensive', 'compute', 'concentrate',
            'concept', 'concern', 'conclude', 'concrete', 'condition', 'conduct', 'conference',
            'confidence', 'confirm', 'conflict', 'confuse', 'connect', 'conscious', 'consensus',
            'consequence', 'conservation', 'consider', 'consist', 'constant', 'construct',
            'consume', 'contact', 'contain', 'contemporary', 'content', 'contest', 'context',
            'contract', 'contrast', 'contribute', 'control', 'controversy', 'convention',
            'conversation', 'convert', 'convince', 'cooperate', 'coordinate', 'cope',
            'copy', 'copyright', 'corner', 'corporate', 'correct', 'correlate', 'council',
            'count', 'country', 'county', 'couple', 'courage', 'course', 'court', 'cousin',
            'cover', 'crack', 'craft', 'crash', 'create', 'creative', 'credit', 'crew',
            'crime', 'crisis', 'criteria', 'critical', 'crop', 'cross', 'crucial', 'cultural',
            'culture', 'current', 'curriculum', 'custom', 'customer', 'cycle', 'daily',
            'damage', 'danger', 'database', 'daughter', 'deadline', 'debate', 'debt', 'decade',
            'decide', 'decision', 'declare', 'decline', 'decorate', 'decrease', 'dedicate',
            'defeat', 'defend', 'define', 'definite', 'degree', 'delay', 'deliberate',
            'delicate', 'deliver', 'demand', 'democracy', 'demonstrate', 'deny', 'department',
            'departure', 'depend', 'depict', 'deposit', 'depression', 'derive', 'describe',
            'desert', 'design', 'designer', 'desire', 'desk', 'desperate', 'despite',
            'destination', 'destroy', 'detail', 'detect', 'develop', 'device', 'devote',
            'diagram', 'dialogue', 'diet', 'differ', 'digital', 'dignity', 'dilemma',
            'dimension', 'diploma', 'direct', 'direction', 'disagree', 'disappear', 'disaster',
            'discipline', 'disclose', 'discount', 'discover', 'discuss', 'disease', 'display',
            'dispute', 'distance', 'distinct', 'distribute', 'district', 'disturb', 'diverse',
            'document', 'domain', 'domestic', 'dominant', 'double', 'downtown', 'drama',
            'dramatic', 'draw', 'driver', 'dynamic', 'economy', 'edition', 'educate',
            'effective', 'efficiency', 'effort', 'elaborate', 'election', 'element', 'eliminate',
            'embrace', 'emerge', 'emission', 'emotion', 'emperor', 'emphasis', 'empire',
            'employ', 'enable', 'enclose', 'encounter', 'encourage', 'endeavor', 'enforce',
            'engage', 'engine', 'enhance', 'enjoy', 'enormous', 'enough', 'ensure', 'enterprise',
            'entertain', 'entire', 'entrance', 'entry', 'environment', 'episode', 'equal',
            'equip', 'equivalent', 'era', 'error', 'escape', 'essential', 'establish',
            'estate', 'estimate', 'ethical', 'evaluate', 'event', 'eventually', 'evidence',
            'evolve', 'exact', 'examine', 'example', 'exceed', 'excellent', 'exception',
            'excess', 'exchange', 'excite', 'exclude', 'execute', 'exercise', 'exhibit',
            'expand', 'expect', 'expense', 'experiment', 'expert', 'explain', 'explicit',
            'exploit', 'explore', 'explosion', 'export', 'expose', 'extend', 'extensive',
            'extent', 'external', 'extract', 'extraordinary', 'extreme', 'facility', 'factor',
            'faculty', 'fade', 'fail', 'failure', 'fair', 'faith', 'familiar', 'fantasy',
            'fashion', 'fatal', 'fate', 'favor', 'feature', 'federal', 'feedback', 'female',
            'festival', 'fiction', 'field', 'figure', 'filter', 'finance', 'finding', 'finite',
            'firm', 'fiscal', 'fix', 'flame', 'flash', 'flexible', 'flight', 'float', 'flood',
            'flourish', 'flow', 'focus', 'force', 'foreign', 'forever', 'formula', 'fortune',
            'forum', 'forward', 'foster', 'foundation', 'fraction', 'fragile', 'framework',
            'freedom', 'frequency', 'friendly', 'frontier', 'frozen', 'fruit', 'function',
            'funding', 'further', 'future', 'galaxy', 'gallery', 'garden', 'gateway', 'gather',
            'general', 'generate', 'generous', 'genetic', 'genius', 'gentle', 'genuine',
            'gesture', 'glacier', 'global', 'glory', 'govern', 'grab', 'grace', 'gradual',
            'grant', 'graphic', 'grateful', 'gravity', 'guarantee', 'guidance', 'guilty',
            'habitat', 'handful', 'handle', 'happen', 'harbor', 'hardly', 'harmony', 'harvest',
            'health', 'heaven', 'height', 'heritage', 'hero', 'hidden', 'highlight', 'highway',
            'history', 'honest', 'horizon', 'horror', 'hostile', 'household', 'housing',
            'humble', 'humor', 'hundred', 'hunter', 'hunting', 'husband', 'hybrid', 'hypothesis',
            'ideal', 'identify', 'ignorant', 'illegal', 'illusion', 'illustrate', 'imagine',
            'immense', 'immigrant', 'immune', 'impact', 'implement', 'implicate', 'implicit',
            'import', 'impose', 'impress', 'imprison', 'improve', 'impulse', 'incident',
            'incline', 'include', 'income', 'incorporate', 'increase', 'incredible', 'indicate',
            'indirect', 'individual', 'industry', 'inevitable', 'infant', 'infect', 'inflation',
            'influence', 'inform', 'infrastructure', 'inherit', 'inhibit', 'initial',
            'initiate', 'injection', 'injure', 'inmate', 'inner', 'innocent', 'innovation',
            'input', 'inquiry', 'insect', 'insert', 'insight', 'inspect', 'inspire', 'install',
            'instance', 'instant', 'instead', 'instinct', 'institute', 'instruct', 'insurance',
            'intact', 'integrate', 'intellectual', 'intelligence', 'intend', 'intense',
            'intention', 'interact', 'interest', 'interface', 'interfere', 'interior',
            'internal', 'interpret', 'interval', 'intervene', 'intimate', 'invade', 'invent',
            'invest', 'investigate', 'invisible', 'invitation', 'involve', 'isolate', 'joint',
            'journal', 'journey', 'judge', 'judgment', 'judicial', 'junction', 'justice',
            'justify', 'kernel', 'keyword', 'kingdom', 'kitchen', 'knowledge', 'landmark',
            'landscape', 'language', 'launch', 'lawyer', 'layout', 'leadership', 'league',
            'lecture', 'legacy', 'legend', 'legislation', 'legitimate', 'leisure', 'lethal',
            'liberal', 'liberty', 'library', 'license', 'lifestyle', 'lifetime', 'lightning',
            'likelihood', 'limited', 'linear', 'linguistic', 'liquid', 'literacy', 'literary',
            'literature', 'litigation', 'locate', 'logical', 'logistics', 'lottery', 'loyalty',
            'luxury', 'machine', 'magazine', 'magic', 'magnetic', 'maintain', 'majority',
            'manager', 'mandate', 'manifest', 'manipulate', 'manner', 'manual', 'manufacture',
            'margin', 'marine', 'marriage', 'massive', 'master', 'material', 'mathematics',
            'matter', 'mature', 'maximum', 'mayor', 'meaning', 'measure', 'mechanism',
            'mediate', 'medical', 'medium', 'member', 'memory', 'mental', 'mention', 'mentor',
            'merchant', 'mercy', 'merely', 'merger', 'merit', 'message', 'metal', 'metaphor',
            'method', 'midnight', 'migrant', 'military', 'million', 'mineral', 'minimal',
            'minimum', 'minister', 'ministry', 'minority', 'miracle', 'mirror', 'misery',
            'mission', 'mixture', 'mobile', 'moderate', 'modern', 'modest', 'modify',
            'module', 'moment', 'monetary', 'monitor', 'monopoly', 'monster', 'monthly',
            'monument', 'morale', 'mortal', 'mortgage', 'motion', 'motivate', 'motive',
            'mountain', 'movement', 'multiple', 'municipal', 'murder', 'muscle', 'musical',
            'mutual', 'mysterious', 'narrow', 'national', 'native', 'natural', 'nature',
            'navigation', 'nearby', 'necessary', 'negative', 'negotiate', 'neighbor', 'neither',
            'nervous', 'network', 'neutral', 'never', 'nevertheless', 'nominal', 'nominate',
            'nonprofit', 'normal', 'normally', 'northern', 'notable', 'notebook', 'notion',
            'novel', 'nowhere', 'nuclear', 'numerous', 'nurture', 'object', 'objective',
            'obligation', 'observe', 'obstacle', 'obtain', 'obvious', 'occasion', 'occupy',
            'offense', 'official', 'offspring', 'ongoing', 'opening', 'operate', 'opinion',
            'opponent', 'opportunity', 'oppose', 'opposite', 'optical', 'optimism', 'option',
            'orbit', 'orchestra', 'ordinary', 'organic', 'organize', 'orient', 'original',
            'originate', 'otherwise', 'outbreak', 'outcome', 'outline', 'outlook', 'output',
            'outrage', 'outside', 'overall', 'overcome', 'overlap', 'overseas', 'overview',
            'overwhelm', 'own', 'ownership', 'oxygen', 'ozone', 'package', 'painful',
            'painting', 'palace', 'panel', 'panic', 'parade', 'paragraph', 'parallel',
            'parameter', 'parent', 'parish', 'parliament', 'participate', 'particular',
            'partly', 'partner', 'passage', 'passion', 'passive', 'password', 'patent',
            'pathway', 'patience', 'patient', 'patrol', 'pattern', 'payment', 'penalty',
            'pending', 'penetrate', 'pension', 'perceive', 'percent', 'perception', 'perfect',
            'perform', 'perhaps', 'period', 'permanent', 'permission', 'persist', 'personality',
            'perspective', 'persuade', 'petition', 'pharmacy', 'phase', 'phenomenon', 'philosophy',
            'phrase', 'physical', 'physician', 'pilot', 'pipeline', 'planet', 'planning',
            'platform', 'pleasure', 'pledge', 'plenty', 'plight', 'plot', 'poetry', 'poison',
            'police', 'policy', 'polish', 'political', 'pollution', 'popular', 'population',
            'portfolio', 'portion', 'portrait', 'position', 'positive', 'possess', 'possible',
            'poster', 'potato', 'potential', 'poverty', 'powder', 'practical', 'practice',
            'preach', 'precede', 'precious', 'precise', 'predict', 'prefer', 'pregnant',
            'prejudice', 'preliminary', 'premier', 'premise', 'premium', 'preparation',
            'prescribe', 'presence', 'present', 'preserve', 'president', 'pressure', 'presume',
            'pretend', 'prevail', 'prevent', 'previous', 'pride', 'priest', 'primary',
            'prince', 'princess', 'principal', 'principle', 'print', 'prior', 'priority',
            'prison', 'privacy', 'private', 'privilege', 'prize', 'probably', 'probe',
            'problem', 'procedure', 'proceed', 'process', 'produce', 'product', 'profession',
            'profile', 'profit', 'program', 'progress', 'project', 'prominent', 'promise',
            'promote', 'prompt', 'proof', 'proper', 'property', 'proportion', 'proposal',
            'propose', 'prosecute', 'prospect', 'protect', 'protein', 'protest', 'protocol',
            'provide', 'province', 'provision', 'provoke', 'psychological', 'publication',
            'publicity', 'publish', 'pulse', 'purchase', 'pursue', 'puzzle', 'qualify',
            'quarter', 'queen', 'query', 'quest', 'question', 'queue', 'radical', 'railway',
            'range', 'rapid', 'rarely', 'rather', 'rating', 'ratio', 'rational', 'reader',
            'readily', 'reading', 'reality', 'realize', 'reasonable', 'rebel', 'recall',
            'receipt', 'receive', 'recent', 'reception', 'recession', 'recipe', 'recipient',
            'reckon', 'recognize', 'recommend', 'record', 'recover', 'recruit', 'reduce',
            'refer', 'reference', 'reflect', 'reform', 'refuge', 'refuse', 'region', 'register',
            'regret', 'regulate', 'rehabilitate', 'reign', 'reinforce', 'reject', 'relate',
            'release', 'relevant', 'relief', 'religion', 'relocate', 'rely', 'remain',
            'remark', 'remedy', 'remember', 'remind', 'remote', 'remove', 'render', 'renew',
            'rental', 'reopen', 'repair', 'repeat', 'replace', 'report', 'represent',
            'reproduce', 'republic', 'reputation', 'request', 'require', 'rescue', 'research',
            'resemble', 'reserve', 'reside', 'resident', 'resign', 'resist', 'resolution',
            'resolve', 'resort', 'resource', 'respond', 'responsible', 'restaurant', 'restore',
            'restrict', 'result', 'resume', 'retail', 'retain', 'retire', 'retreat', 'return',
            'reveal', 'revenue', 'reverse', 'review', 'revise', 'revolution', 'reward',
            'rhetoric', 'rhythm', 'riddle', 'ridge', 'rigid', 'rising', 'rival', 'rocket',
            'romance', 'rough', 'routine', 'royal', 'ruling', 'rural', 'sacred', 'sacrifice',
            'safety', 'salary', 'sample', 'satellite', 'satisfy', 'scale', 'scandal',
            'scatter', 'scenario', 'schedule', 'scholar', 'science', 'scissors', 'scope',
            'scratch', 'screen', 'script', 'scrutiny', 'sculpture', 'season', 'secondary',
            'secret', 'section', 'sector', 'secure', 'segment', 'select', 'senator', 'senior',
            'sensation', 'sensitive', 'sentence', 'separate', 'sequence', 'serial', 'session',
            'setting', 'settle', 'severe', 'shadow', 'shallow', 'shame', 'shaping', 'shelter',
            'shield', 'shift', 'shipping', 'shock', 'shooting', 'shortly', 'shower', 'shrimp',
            'signal', 'significant', 'silence', 'silver', 'similar', 'simple', 'simulate',
            'simultaneous', 'sinner', 'sitting', 'situated', 'situation', 'skeleton', 'skeptic',
            'sketch', 'skilled', 'slavery', 'slightly', 'slogan', 'smooth', 'snapshot',
            'society', 'software', 'solar', 'soldier', 'solely', 'solemn', 'solid', 'solution',
            'somewhat', 'sophisticated', 'sorrow', 'sorting', 'source', 'sovereign', 'spacing',
            'speaker', 'specialist', 'species', 'specific', 'spectacle', 'spectrum', 'speech',
            'spending', 'spirit', 'spiritual', 'sponsor', 'sport', 'spotlight', 'spread',
            'spring', 'squad', 'stable', 'stadium', 'staff', 'standard', 'standing', 'startup',
            'statement', 'statue', 'status', 'steady', 'storage', 'strange', 'strategy',
            'stream', 'strength', 'stress', 'stretch', 'strict', 'strike', 'string', 'stroke',
            'structure', 'struggle', 'student', 'studio', 'submit', 'subsequent', 'subsidy',
            'substance', 'substantial', 'subtle', 'suburb', 'succeed', 'success', 'suffer',
            'sufficient', 'suggest', 'suitable', 'summit', 'sunlight', 'superb', 'superior',
            'supplement', 'supply', 'support', 'suppose', 'supreme', 'surface', 'surgery',
            'surplus', 'surprise', 'surrender', 'surround', 'survey', 'survive', 'suspect',
            'suspend', 'sustain', 'swallow', 'symbol', 'sympathy', 'symptom', 'syndrome',
            'synthesis', 'system', 'tablet', 'tactics', 'talent', 'target', 'tariff', 'tattoo',
            'taxation', 'teacher', 'technique', 'technology', 'temple', 'temporary', 'tempt',
            'tendency', 'tender', 'tennis', 'tension', 'terminal', 'territory', 'terror',
            'testify', 'texture', 'theater', 'theory', 'therapy', 'thorough', 'threaten',
            'thrill', 'thriving', 'through', 'throughout', 'thunder', 'timber', 'tissue',
            'tobacco', 'tolerance', 'torture', 'tourist', 'tournament', 'track', 'trademark',
            'tradition', 'traffic', 'tragedy', 'trail', 'trailer', 'trainer', 'trait',
            'transaction', 'transfer', 'transform', 'transit', 'transmit', 'transparent',
            'transport', 'trauma', 'treasure', 'treaty', 'tremendous', 'trend', 'trial',
            'triangle', 'tribe', 'tribute', 'trigger', 'triumph', 'troop', 'tropical',
            'trouble', 'truck', 'trustee', 'tuition', 'tunnel', 'turbine', 'tutor', 'typical',
            'ultimate', 'umbrella', 'unable', 'unanimous', 'undergo', 'undergraduate',
            'underlying', 'undermine', 'undertake', 'uniform', 'unify', 'union', 'unique',
            'universal', 'universe', 'unknown', 'unleash', 'unlikely', 'unusual', 'update',
            'upgrade', 'uphold', 'uprising', 'urban', 'urgent', 'utility', 'utilize', 'utmost',
            'vacuum', 'valid', 'valuable', 'valley', 'variation', 'variety', 'various',
            'vehicle', 'velocity', 'venture', 'verdict', 'version', 'vessel', 'veteran',
            'viable', 'vibrant', 'victim', 'victory', 'video', 'viewpoint', 'village',
            'violate', 'violence', 'virtual', 'virtue', 'visible', 'vision', 'visitor',
            'visual', 'vital', 'vitamin', 'vivid', 'vocabulary', 'volcano', 'volume',
            'voluntary', 'volunteer', 'voting', 'vulnerable', 'wage', 'wander', 'warrant',
            'warrior', 'wealth', 'weapon', 'welfare', 'western', 'whereas', 'widespread',
            'wilderness', 'willing', 'wisdom', 'withdraw', 'witness', 'workshop', 'worship',
            'worthy', 'wound', 'wrap', 'writing', 'youngster', 'youthful', 'zeal', 'zenith'
        ],
        hard: [
            'aberration', 'abnegate', 'abscond', 'abstemious', 'accolade', 'accretion',
            'acrimony', 'admonish', 'adulation', 'aesthetic', 'alacrity', 'ambiguous',
            'ameliorate', 'anachronism', 'anathema', 'anomaly', 'antebellum', 'antipathy',
            'apathetic', 'appease', 'arcane', 'arduous', 'articulate', 'ascetic', 'asinine',
            'assuage', 'auspicious', 'austere', 'avarice', 'avenge', 'bellicose', 'benevolent',
            'berate', 'bifurcate', 'blandish', 'bombastic', 'boorish', 'brazen', 'bucolic',
            'burgeon', 'burnish', 'cacophony', 'calumny', 'capricious', 'castigate', 'caustic',
            'censure', 'chagrin', 'charisma', 'chicanery', 'circumspect', 'clamor', 'clemency',
            'coalesce', 'cogent', 'commensurate', 'compendium', 'complacent', 'conciliatory',
            'concomitant', 'condescend', 'congenial', 'congruent', 'conjecture', 'conscientious',
            'consecrate', 'conspicuous', 'contempt', 'contentious', 'contravene', 'contrite',
            'conundrum', 'convivial', 'copious', 'corroborate', 'credule', 'cryptic',
            'culpable', 'cumbersome', 'curmudgeon', 'cynical', 'decorum', 'deference',
            'delineate', 'deluge', 'demagogue', 'demeanor', 'denigrate', 'denouement',
            'deprecate', 'derelict', 'desiccate', 'despondent', 'destitute', 'dexterous',
            'didactic', 'diffident', 'dilatory', 'discerning', 'discordant', 'disdain',
            'disingenuous', 'disparage', 'disparate', 'disseminate', 'dissipate', 'dissolution',
            'distraught', 'docile', 'dogmatic', 'dormant', 'draconian', 'dubious', 'dulcet',
            'duplicity', 'ebullient', 'ecclesiastical', 'eclectic', 'efficacy', 'effrontery',
            'egalitarian', 'egregious', 'elegy', 'elicit', 'eloquent', 'elucidate', 'emaciate',
            'emanate', 'embellish', 'empirical', 'emulate', 'encompass', 'encumber', 'endemic',
            'enervate', 'engender', 'enigmatical', 'enmity', 'enormity', 'ephemeral',
            'equanimity', 'equivocator', 'erudite', 'escalate', 'esoteric', 'espouse',
            'ethereal', 'euphemism', 'evanescent', 'exacerbate', 'exalt', 'exasperate',
            'excoriate', 'exculpate', 'exemplary', 'exhort', 'exigent', 'exonerate', 'expatriate',
            'expedite', 'explicit', 'expropriate', 'expunge', 'extenuate', 'extol', 'extraneous',
            'extricate', 'exuberant', 'facade', 'facilitate', 'fallacious', 'fathom',
            'fatuous', 'fawn', 'feckless', 'fervent', 'fiasco', 'flaccid', 'flippant',
            'florid', 'forbearance', 'foreboding', 'fortitude', 'frenetic', 'frivolous',
            'frugal', 'fulminate', 'furtive', 'futile', 'garrulous', 'germane', 'grandiose',
            'gratuitous', 'gregarious', 'hackneyed', 'hapless', 'harangue', 'harbinger',
            'hedonism', 'heinous', 'heresy', 'hermetic', 'hiatus', 'hierarchy', 'hubris',
            'iconoclast', 'idiosyncratic', 'ignominy', 'illicit', 'immutable', 'impasse',
            'impeccable', 'impertinent', 'implacable', 'implicit', 'importune', 'impregnable',
            'improvident', 'impudent', 'impugn', 'impunity', 'inadvertent', 'inalienable',
            'incandescent', 'incapacitate', 'incendiary', 'inchoate', 'incipient', 'incisive',
            'incongruous', 'incorrigible', 'incredulous', 'incumbent', 'indelible', 'indigent',
            'indolent', 'indomitable', 'ineffable', 'ineluctable', 'inexorable', 'infallible',
            'ingenuous', 'inimical', 'innate', 'inscrutable', 'insidious', 'insolent',
            'instigate', 'insular', 'intangible', 'intransigent', 'intrepid', 'inundate',
            'invective', 'inveterate', 'inviolable', 'irascible', 'irreverent', 'itinerant',
            'juxtapose', 'knell', 'laconic', 'lambaste', 'languid', 'largesse', 'lassitude',
            'laudable', 'lethargic', 'levity', 'litigious', 'loquacious', 'lucid', 'lugubrious',
            'magnanimous', 'malfeasance', 'malinger', 'malleable', 'maelstrom', 'mandate',
            'manifesto', 'martinet', 'maudlin', 'maverick', 'mendacious', 'mercurial',
            'meritorious', 'metamorphosis', 'meticulous', 'milieu', 'misanthrope', 'mitigate',
            'mollify', 'morose', 'mundane', 'munificent', 'myopic', 'nadir', 'nascent',
            'nebulous', 'nefarious', 'nihilism', 'nonchalant', 'nonpareil', 'nostalgia',
            'notorious', 'nuance', 'obdurate', 'obfuscate', 'oblique', 'oblivious', 'obsequious',
            'obsolete', 'obstinate', 'officious', 'omnipotent', 'omniscient', 'onerous',
            'opaque', 'opprobrium', 'ostentatious', 'painstaking', 'palatable', 'palliate',
            'palpable', 'panacea', 'paradigm', 'paradox', 'paragon', 'parochial', 'parsimonious',
            'partisan', 'patronize', 'paucity', 'pedantic', 'pejorative', 'penchant', 'penitent',
            'penurious', 'perfidious', 'perfunctory', 'peripatetic', 'pernicious', 'perpetuate',
            'perspicacious', 'pertinacious', 'pervasive', 'petulant', 'philanthropy', 'phlegmatic',
            'placate', 'platitude', 'plausible', 'plethora', 'poignant', 'polemic', 'ponderous',
            'pragmatic', 'precarious', 'precedent', 'precipitate', 'preclude', 'precocious',
            'predilection', 'preeminent', 'premonition', 'preponderance', 'prerogative',
            'prescient', 'presumptuous', 'prevaricate', 'primordial', 'probity', 'proclivity',
            'prodigious', 'profligate', 'prognosticate', 'proliferate', 'promulgate', 'propensity',
            'prophetic', 'propitiate', 'propitious', 'propriety', 'prosaic', 'proscribe',
            'protean', 'provident', 'provincial', 'proviso', 'prudent', 'pugnacious', 'punctilious',
            'pundit', 'pungent', 'quagmire', 'quandary', 'querulous', 'quiescent', 'quintessence',
            'quixotic', 'quotidian', 'rancor', 'rapacious', 'rarefied', 'raucous', 'recalcitrant',
            'recant', 'reciprocate', 'recluse', 'recondite', 'redoubtable', 'refractory',
            'refute', 'relegate', 'relentless', 'relinquish', 'remonstrate', 'renaissance',
            'renounce', 'replete', 'reprehensible', 'reprobate', 'repudiate', 'requisite',
            'rescind', 'resilient', 'resolute', 'resplendent', 'restitution', 'reticent',
            'retrograde', 'reverent', 'rhetoric', 'ribald', 'rife', 'ruminate', 'rustic',
            'sacrosanct', 'sagacious', 'salient', 'salutary', 'sanctimonious', 'sanguine',
            'sardonic', 'satiate', 'savor', 'scintillate', 'scrupulous', 'scrutinize',
            'sedentary', 'seditious', 'seminal', 'sentient', 'serendipity', 'servile',
            'sibilant', 'solicitous', 'somnolent', 'sonorous', 'sophistry', 'specious',
            'sporadic', 'spurious', 'squalid', 'stagnate', 'stolid', 'stringent', 'strident',
            'subjugate', 'sublime', 'subservient', 'substantiate', 'subterfuge', 'succinct',
            'suffrage', 'sullen', 'sumptuous', 'supercilious', 'superfluous', 'supine',
            'supplant', 'surreptitious', 'susceptible', 'sycophant', 'taciturn', 'tangential',
            'tantamount', 'temerity', 'temperate', 'tenacious', 'tenet', 'terse', 'tirade',
            'torpid', 'totalitarian', 'tractable', 'transgress', 'transient', 'travesty',
            'trepidation', 'truculent', 'truncate', 'tumultuous', 'turpitude', 'ubiquitous',
            'umbrage', 'unconscionable', 'unctuous', 'undermine', 'underscore', 'unequivocal',
            'unprecedented', 'unscrupulous', 'untenable', 'unwitting', 'upbraid', 'urbane',
            'usurp', 'utilitarian', 'vacillate', 'vacuous', 'vagary', 'vainglorious', 'valid',
            'vapid', 'vehement', 'venerate', 'veracious', 'verbose', 'verdant', 'verisimilitude',
            'vestige', 'vicarious', 'vicissitude', 'vigilant', 'vindicate', 'virtuoso',
            'virulent', 'viscous', 'vitiate', 'vituperate', 'vivacious', 'vociferous', 'volatile',
            'voracious', 'warranted', 'wary', 'whimsical', 'wistful', 'zealous', 'zenith'
        ]
    },
    es: {
        name: 'Spanish',
        normal: [
            'el', 'la', 'los', 'las', 'de', 'que', 'y', 'a', 'en', 'un', 'ser', 'se', 'no',
            'haber', 'por', 'con', 'su', 'para', 'como', 'estar', 'tener', 'le', 'lo', 'todo',
            'bien', 'más', 'hacer', 'poder', 'decir', 'este', 'otro', 'ese', 'mismo', 'yo',
            'primero', 'gran', 'sin', 'cada', 'nunca', 'saber', 'qué', 'vez', 'nuevo', 'deber',
            'contra', 'parte', 'donde', 'creer', 'llegar', 'entre', 'siempre', 'llevar',
            'tiempo', 'solo', 'tipo', 'tanto', 'casa', 'hombre', 'mujer', 'amigo', 'trabajo',
            'vida', 'año', 'día', 'mundo', 'país', 'mano', 'ojo', 'cara', 'agua', 'fuego',
            'libro', 'palabra', 'idea', 'nombre', 'valor', 'ley', 'forma', 'caso', 'momento',
            'noche', 'día', 'semana', 'mes', 'año', 'siglo', 'historia', 'arte', 'cultura',
            'familia', 'padre', 'madre', 'hijo', 'hermano', 'hija', 'abuelo', 'niño', 'joven',
            'persona', 'gente', 'pueblo', 'ciudad', 'calle', 'plaza', 'casa', 'puerta',
            'ventana', 'mesa', 'silla', 'cama', 'coche', 'camino', 'aire', 'tierra', 'mar',
            'sol', 'luna', 'estrella', 'flor', 'árbol', 'montaña', 'río', 'bosque', 'campo',
            'animal', 'perro', 'gato', 'caballo', 'pájaro', 'pez', 'rojo', 'verde', 'azul',
            'blanco', 'negro', 'gris', 'amarillo', 'naranja', 'violeta', 'rosa', 'marron',
            'claro', 'oscuro', 'alto', 'bajo', 'largo', 'corto', 'grande', 'pequeño', 'nuevo',
            'viejo', 'joven', 'bueno', 'malo', 'mejor', 'peor', 'bonito', 'feo', 'rico',
            'pobre', 'fuerte', 'débil', 'rápido', 'lento', 'caliente', 'frío', 'duro',
            'blando', 'suave', 'difícil', 'fácil', 'seguro', 'peligroso', 'importante',
            'necesario', 'posible', 'imposible', 'verdadero', 'falso', 'libre', 'justo',
            'común', 'raro', 'simple', 'complejo', 'público', 'privado', 'social', 'político',
            'económico', 'cultural', 'natural', 'humano', 'general', 'particular', 'internacional',
            'nacional', 'regional', 'local', 'urbano', 'rural', 'antiguo', 'moderno', 'clásico',
            'popular', 'típico', 'especial', 'normal', 'extraño', 'maravilloso', 'terrible',
            'fantástico', 'increíble', 'absoluto', 'completo', 'parcial', 'total', 'único',
            'doble', 'múltiple', 'mucho', 'poco', 'bastante', 'demasiado', 'casi', 'solo',
            'también', 'además', 'entonces', 'después', 'antes', 'ahora', 'ayer', 'hoy',
            'mañana', 'siempre', 'nunca', 'ya', 'todavía', 'pronto', 'tarde', 'temprano',
            'aquí', 'allí', 'ahora', 'cerca', 'lejos', 'dentro', 'fuera', 'arriba', 'abajo',
            'adelante', 'atrás', 'encima', 'debajo', 'delante', 'detrás', 'alrededor', 'medio',
            'mientras', 'aunque', 'porque', 'pues', 'sino', 'pero', 'como', 'cuando', 'donde',
            'mientras', 'según', 'entre', 'hacia', 'hasta', 'desde', 'durante', 'mediante',
            'salvo', 'excepto', 'incluso', 'menos', 'más', 'tan', 'tanto', 'qué', 'quién',
            'cuál', 'cómo', 'dónde', 'cuándo', 'cuánto', 'por qué', 'para qué', 'a qué'
        ]
    },
    fr: {
        name: 'French',
        normal: [
            'le', 'la', 'les', 'de', 'des', 'du', 'un', 'une', 'et', 'est', 'sont', 'dans',
            'pour', 'sur', 'avec', 'par', 'pas', 'plus', 'tout', 'leur', 'lui', 'elle', 'ils',
            'ont', 'fait', 'faire', 'être', 'avoir', 'aller', 'pouvoir', 'vouloir', 'devoir',
            'savoir', 'voir', 'venir', 'dire', 'prendre', 'donner', 'mettre', 'parler', 'aimer',
            'passer', 'chercher', 'trouver', 'laisser', 'rester', 'tenir', 'croire', 'entendre',
            'comprendre', 'connaître', 'penser', 'rendre', 'suivre', 'vivre', 'mourir', 'naître',
            'temps', 'chose', 'homme', 'femme', 'monde', 'jour', 'an', 'enfant', 'personne',
            'ami', 'amour', 'travail', 'argent', 'ville', 'pays', 'maison', 'eau', 'feu', 'terre',
            'soleil', 'lune', 'ciel', 'mer', 'vent', 'nuit', 'matin', 'soir', 'bon', 'mauvais',
            'grand', 'petit', 'beau', 'joli', 'jeune', 'vieux', 'nouveau', 'haut', 'bas', 'large',
            'étroit', 'long', 'court', 'fort', 'faible', 'lourd', 'léger', 'plein', 'vide',
            'dur', 'doux', 'chaud', 'froid', 'sec', 'humide', 'clair', 'sombre', 'vrai', 'faux',
            'certain', 'autre', 'même', 'tel', 'quel', 'chaque', 'plusieurs', 'tout', 'aucun',
            'nul', 'assez', 'beaucoup', 'peu', 'trop', 'environ', 'presque', 'si', 'très',
            'aussi', 'bien', 'mal', 'mieux', 'pire', 'jamais', 'parfois', 'souvent', 'toujours',
            'partout', 'ailleurs', 'ici', 'là', 'près', 'loin', 'dessus', 'dessous', 'dedans',
            'dehors', 'avant', 'après', 'hier', 'aujourd\'hui', 'demain', 'maintenant', 'bientôt',
            'enfin', 'alors', 'puis', 'ensuite', 'd\'abord', 'cependant', 'pourtant', 'donc',
            'car', 'mais', 'ou', 'ni', 'que', 'quand', 'comment', 'pourquoi', 'combien', 'qui',
            'dont', 'où', 'lequel', 'auquel', 'duquel', 'vers', 'sans', 'chez', 'entre', 'sous'
        ]
    },
    de: {
        name: 'German',
        normal: [
            'der', 'die', 'das', 'den', 'dem', 'des', 'ein', 'eine', 'einen', 'einem', 'eines',
            'und', 'oder', 'aber', 'denn', 'sondern', 'weil', 'dass', 'wenn', 'als', 'wie',
            'bei', 'mit', 'nach', 'aus', 'von', 'zu', 'an', 'auf', 'vor', 'für', 'um', 'durch',
            'gegen', 'ohne', 'bis', 'über', 'unter', 'neben', 'zwischen', 'hinter', 'vor',
            'ich', 'du', 'er', 'sie', 'es', 'wir', 'ihr', 'Sie', 'mein', 'dein', 'sein', 'ihr',
            'unser', 'euer', 'Ihr', 'haben', 'sein', 'werden', 'können', 'müssen', 'dürfen',
            'sollen', 'wollen', 'mögen', 'tun', 'machen', 'sagen', 'geben', 'kommen', 'gehen',
            'sehen', 'lassen', 'bringen', 'nehmen', 'finden', 'halten', 'liegen', 'setzen',
            'stehen', 'schreiben', 'lesen', 'sprechen', 'denken', 'glauben', 'wissen', 'verstehen',
            'arbeiten', 'spielen', 'lernen', 'wohnen', 'reisen', 'kaufen', 'verkaufen', 'zahlen',
            'gross', 'klein', 'schnell', 'langsam', 'neu', 'alt', 'jung', 'gut', 'schlecht',
            'schön', 'hässlich', 'reich', 'arm', 'stark', 'schwach', 'hart', 'weich', 'warm',
            'kalt', 'trocken', 'nass', 'hell', 'dunkel', 'frei', 'wichtig', 'richtig', 'falsch',
            'ganz', 'halb', 'viel', 'wenig', 'alle', 'manche', 'mehrere', 'einige', 'nur',
            'auch', 'schon', 'noch', 'erst', 'zuerst', 'damn', 'dann', 'bald', 'sofort', 'spät',
            'früh', 'immer', 'nie', 'manchmal', 'oft', 'selten', 'hier', 'dort', 'da', 'links',
            'rechts', 'vorn', 'hinten', 'innen', 'aussen', 'oben', 'unten', 'Mensch', 'Mann',
            'Frau', 'Kind', 'Haus', 'Auto', 'Stadt', 'Land', 'Welt', 'Arbeit', 'Schule',
            'Freund', 'Familie', 'Name', 'Zahl', 'Tag', 'Woche', 'Monat', 'Jahr', 'Zeit',
            'Stunde', 'Minute', 'Sekunde', 'Morgen', 'Abend', 'Nacht', 'Montag', 'Dienstag',
            'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag', 'Januar', 'Februar',
            'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober',
            'November', 'Dezember', 'Frühling', 'Sommer', 'Herbst', 'Winter'
        ]
    },
    pt: {
        name: 'Portuguese',
        normal: [
            'o', 'a', 'os', 'as', 'de', 'do', 'da', 'em', 'no', 'na', 'para', 'por', 'com',
            'como', 'mas', 'mais', 'menos', 'muito', 'pouco', 'todo', 'outro', 'mesmo', 'tão',
            'cada', 'ainda', 'já', 'sempre', 'nunca', 'depois', 'antes', 'agora', 'aqui', 'ali',
            'ser', 'estar', 'ter', 'haver', 'fazer', 'dizer', 'poder', 'querer', 'saber',
            'dever', 'ver', 'vir', 'dar', 'ficar', 'levar', 'deixar', 'passar', 'chegar',
            'entrar', 'sair', 'olhar', 'achar', 'pensar', 'acreditar', 'falar', 'contar',
            'perguntar', 'responder', 'mostrar', 'trabalhar', 'estudar', 'aprender', 'ensinar',
            'ler', 'escrever', 'ouvir', 'sentir', 'comer', 'beber', 'dormir', 'viver', 'morrer',
            'nascer', 'crescer', 'abrir', 'fechar', 'começar', 'terminar', 'continuar', 'mudar',
            'homem', 'mulher', 'criança', 'pessoa', 'amigo', 'família', 'pai', 'mãe', 'filho',
            'irmão', 'casa', 'carro', 'rua', 'cidade', 'país', 'mundo', 'terra', 'mar', 'sol',
            'lua', 'céu', 'noite', 'dia', 'manhã', 'tarde', 'ano', 'mês', 'semana', 'hora',
            'tempo', 'vida', 'amor', 'trabalho', 'escola', 'livro', 'palavra', 'nome', 'número',
            'coisa', 'parte', 'lugar', 'caso', 'vez', 'bem', 'mal', 'bom', 'mau', 'grande',
            'pequeno', 'novo', 'velho', 'jovem', 'alto', 'baixo', 'bonito', 'feio', 'rico',
            'pobre', 'forte', 'fraco', 'rápido', 'lento', 'quente', 'frio', 'fácil', 'difícil',
            'caro', 'barato', 'limpo', 'sujo', 'claro', 'escuro', 'seco', 'molhado', 'alegre',
            'triste', 'feliz', 'bravo', 'calmo', 'primeiro', 'último', 'melhor', 'pior',
            'maior', 'menor', 'nacional', 'internacional', 'social', 'político', 'econômico',
            'cultural', 'histórico', 'natural', 'humano', 'público', 'privado', 'possível',
            'impossível', 'verdadeiro', 'falso', 'livre', 'justo', 'comum', 'raro', 'simples',
            'importante', 'necessário', 'urgente', 'final', 'geral', 'particular', 'principal'
        ]
    },
    it: {
        name: 'Italian',
        normal: [
            'il', 'lo', 'la', 'i', 'gli', 'le', 'del', 'dello', 'della', 'dei', 'degli', 'delle',
            'al', 'allo', 'alla', 'ai', 'agli', 'alle', 'dal', 'dallo', 'dalla', 'dai', 'dagli',
            'dalle', 'nel', 'nello', 'nella', 'nei', 'negli', 'nelle', 'un', 'uno', 'una',
            'e', 'ed', 'o', 'ma', 'però', 'anche', 'come', 'che', 'chi', 'cui', 'quale', 'quanto',
            'dove', 'quando', 'perché', 'se', 'mentre', 'dunque', 'allora', 'quindi', 'cioè',
            'infatti', 'invece', 'non', 'né', 'più', 'meno', 'molto', 'poco', 'tanto', 'troppo',
            'abbastanza', 'ancora', 'già', 'sempre', 'mai', 'spesso', 'raramente', 'adesso',
            'ora', 'subito', 'dopo', 'prima', 'poi', 'oggi', 'domani', 'ieri', 'presto', 'tardi',
            'sempre', 'mai', 'qua', 'là', 'qui', 'lì', 'sopra', 'sotto', 'dentro', 'fuori',
            'avanti', 'indietro', 'vicino', 'lontano', 'insieme', 'solo', 'anche', 'neppure',
            'essere', 'avere', 'fare', 'dire', 'potere', 'volere', 'sapere', 'dovere', 'stare',
            'andare', 'venire', 'dare', 'prendere', 'lasciare', 'mettere', 'trovare', 'chiamare',
            'parlare', 'dire', 'chiedere', 'rispondere', 'aprire', 'chiudere', 'entrare', 'uscire',
            'partire', 'arrivare', 'tornare', 'vivere', 'morire', 'nascere', 'mangiare', 'bere',
            'dormire', 'leggere', 'scrivere', 'ascoltare', 'sentire', 'capire', 'imparare',
            'lavorare', 'studiare', 'giocare', 'viaggiare', 'comprare', 'vendere', 'pagare',
            'casa', 'città', 'paese', 'mondo', 'terra', 'mare', 'cielo', 'sole', 'luna', 'stella',
            'uomo', 'donna', 'bambino', 'persona', 'amico', 'famiglia', 'padre', 'madre', 'figlio',
            'fratello', 'sorella', 'marito', 'moglie', 'nome', 'vita', 'amore', 'tempo', 'lavoro',
            'scuola', 'libro', 'parola', 'casa', 'strada', 'piazza', 'porta', 'finestra', 'tavolo',
            'sedia', 'letto', 'macchina', 'treno', 'aereo', 'bella', 'buono', 'cattivo', 'grande',
            'piccolo', 'nuovo', 'vecchio', 'giovane', 'alto', 'basso', 'lungo', 'corto', 'largo',
            'stretto', 'forte', 'debole', 'veloce', 'lento', 'caldo', 'freddo', 'secco', 'bagnato',
            'chiaro', 'scuro', 'facile', 'difficile', 'vero', 'falso', 'libero', 'giusto', 'ricco',
            'povero', 'bello', 'brutto', 'allegro', 'triste', 'felice', 'arrabbiato', 'primo',
            'ultimo', 'migliore', 'peggiore', 'importante', 'possibile', 'semplice', 'speciale'
        ]
    },
    nl: {
        name: 'Dutch',
        normal: [
            'de', 'het', 'een', 'van', 'in', 'op', 'met', 'voor', 'dat', 'die', 'niet', 'en',
            'zijn', 'ook', 'als', 'aan', 'nog', 'bij', 'uit', 'door', 'naar', 'om', 'te',
            'worden', 'hebben', 'zullen', 'kunnen', 'moeten', 'mogen', 'weten', 'willen',
            'zeggen', 'maken', 'gaan', 'komen', 'staan', 'zien', 'doen', 'geven', 'nemen',
            'brengen', 'houden', 'zoeken', 'vinden', 'denken', 'geloven', 'vragen', 'antwoorden',
            'werken', 'spelen', 'leren', 'wonen', 'reizen', 'kopen', 'verkopen', 'betalen',
            'eten', 'drinken', 'slapen', 'lezen', 'schrijven', 'horen', 'voelen', 'wachten',
            'lopen', 'rijden', 'vliegen', 'vallen', 'liggen', 'zitten', 'leven', 'sterven',
            'mens', 'man', 'vrouw', 'kind', 'huis', 'auto', 'stad', 'land', 'wereld', 'werk',
            'school', 'boek', 'woord', 'naam', 'getal', 'tijd', 'dag', 'week', 'maand', 'jaar',
            'uur', 'minuut', 'seconde', 'morgen', 'avond', 'nacht', 'groot', 'klein', 'snel',
            'langzaam', 'nieuw', 'oud', 'jong', 'goed', 'slecht', 'mooi', 'lelijk', 'rijk',
            'arm', 'sterk', 'zwak', 'hard', 'zacht', 'warm', 'koud', 'droog', 'nat', 'licht',
            'donker', 'vrij', 'belangrijk', 'juist', 'verkeerd', 'geheel', 'half', 'veel',
            'weinig', 'alleen', 'samen', 'altijd', 'nooit', 'soms', 'vaak', 'zelden', 'hier',
            'daar', 'links', 'rechts', 'voor', 'achter', 'binnen', 'buiten', 'boven', 'beneden',
            'vandaag', 'gisteren', 'morgen', 'nu', 'straks', 'meteen', 'eerst', 'daarna',
            'vriend', 'familie', 'vader', 'moeder', 'zoon', 'dochter', 'broer', 'zus', 'man',
            'vrouw', 'naam', 'leven', 'liefde', 'werk', 'geld', 'water', 'vuur', 'aarde',
            'lucht', 'zon', 'maan', 'ster', 'bloem', 'boom', 'berg', 'rivier', 'zee',
            'dier', 'hond', 'kat', 'paard', 'vogel', 'vis', 'rood', 'groen', 'blauw',
            'wit', 'zwart', 'grijs', 'geel', 'oranje', 'paars', 'roze', 'bruin'
        ]
    },
    ru: {
        name: 'Russian',
        normal: [
            'в', 'на', 'с', 'к', 'по', 'для', 'из', 'у', 'от', 'до', 'за', 'о', 'об', 'при',
            'без', 'через', 'между', 'перед', 'над', 'под', 'около', 'против', 'после', 'во',
            'и', 'а', 'но', 'да', 'или', 'если', 'что', 'как', 'когда', 'где', 'куда', 'откуда',
            'почему', 'зачем', 'потому', 'поэтому', 'однако', 'также', 'тоже', 'ещё', 'уже',
            'не', 'ни', 'всё', 'все', 'этот', 'тот', 'такой', 'какой', 'каждый', 'весь',
            'самый', 'другой', 'иной', 'некоторый', 'один', 'два', 'три', 'четыре', 'пять',
            'шесть', 'семь', 'восемь', 'девять', 'десять', 'хороший', 'плохой', 'большой',
            'маленький', 'новый', 'старый', 'молодой', 'красивый', 'сильный', 'слабый',
            'быстрый', 'медленный', 'тёплый', 'холодный', 'лёгкий', 'тяжёлый', 'трудный',
            'простой', 'важный', 'нужный', 'верный', 'главный', 'общий', 'разный', 'похожий',
            'быть', 'иметь', 'мочь', 'делать', 'сказать', 'говорить', 'знать', 'думать',
            'понимать', 'видеть', 'смотреть', 'слышать', 'слушать', 'чувствовать', 'хотеть',
            'любить', 'жить', 'работать', 'учиться', 'читать', 'писать', 'играть', 'ходить',
            'ездить', 'бегать', 'сидеть', 'стоять', 'лежать', 'спать', 'есть', 'пить',
            'готовить', 'покупать', 'продавать', 'платить', 'брать', 'давать', 'ждать',
            'человек', 'мужчина', 'женщина', 'ребёнок', 'друг', 'семья', 'мать', 'отец',
            'брат', 'сестра', 'сын', 'дочь', 'имя', 'дом', 'город', 'страна', 'мир', 'земля',
            'вода', 'огонь', 'воздух', 'солнце', 'луна', 'звезда', 'небо', 'море', 'река',
            'лес', 'гора', 'поле', 'дорога', 'работа', 'школа', 'книга', 'слово', 'время',
            'день', 'ночь', 'утро', 'вечер', 'неделя', 'месяц', 'год', 'жизнь', 'любовь',
            'собака', 'кошка', 'лошадь', 'птица', 'рыба', 'дерево', 'цветок', 'красный',
            'зелёный', 'синий', 'белый', 'чёрный', 'серый', 'жёлтый', 'оранжевый', 'розовый'
        ]
    },
    ja: {
        name: 'Japanese (Romaji)',
        normal: [
            'konnichiwa', 'arigatou', 'sayounara', 'ohayou', 'konbanwa', 'sumimasen',
            'onegaishimasu', 'hai', 'iie', 'kudasai', 'daijoubu', 'wakarimashita', 'hai',
            'watashi', 'anata', 'kare', 'kanojo', 'koko', 'soko', 'asoko', 'kore', 'sore',
            'are', 'doko', 'dare', 'nani', 'itsu', 'naze', 'ikura', 'dou', 'konnani',
            'taberu', 'nomu', 'suru', 'iku', 'kuru', 'miru', 'kiku', 'hanasu', 'yomu',
            'kaku', 'kau', 'uru', 'toru', 'ageru', 'morau', 'oshieru', 'narau', 'wakaru',
            'dekakeru', 'kaeru', 'matsu', 'tasukeru', 'hajimeru', 'owaru', 'shigoto',
            'gakkou', 'ie', 'kuruma', 'hon', 'pen', 'kami', 'te', 'ashi', 'me', 'mimi',
            'kuchi', 'hana', 'atama', 'karada', 'mizu', 'hi', 'sora', 'umi', 'yama',
            'kawa', 'hana', 'ki', 'tori', 'sakana', 'inu', 'neko', 'uma', 'ookii',
            'chiisai', 'atarashii', 'furui', 'wakai', 'utsukushii', 'takai', 'hikui',
            'hayai', 'osoi', 'atsui', 'samui', 'atatakai', 'suzushii', 'omoi', 'karui',
            'yasashii', 'muzukashii', 'tanoshii', 'kanashii', 'ureshii', 'kowai',
            'ichiban', 'daisuki', 'kirei', 'genki', 'shinpai', 'daijoubu', 'mochiron',
            'chotto', 'sukoshi', 'takusan', 'zenzen', 'yukkuri', 'sugu', 'mou',
            'mada', 'itsumo', 'tokidoki', 'taitei', 'kesshite', 'douzo', 'doumo',
            'hontou', 'maji', 'kamo', 'shinjiru', 'omou', 'kangaeru', 'kokoro',
            'sekai', 'jinsei', 'yuuki', 'kibou', 'yume', 'ai', 'eien', 'shiawase'
        ]
    },
    zh: {
        name: 'Chinese (Pinyin)',
        normal: [
            'wo', 'ni', 'ta', 'wo men', 'ni men', 'ta men', 'zhe', 'na', 'zhe li', 'na li',
            'zhe ge', 'na ge', 'shen me', 'shui', 'zen me', 'zen me yang', 'duo shao', 'ji ge',
            'shi', 'you', 'zai', 'de', 'le', 'bu', 'hen', 'neng', 'hui', 'yao', 'xiang',
            'jue de', 'zhi dao', 'ming bai', 'dong', 'kan', 'ting', 'shuo', 'du', 'xie',
            'zuo', 'qu', 'lai', 'chi', 'he', 'shui', 'zou', 'pao', 'fei', 'zuo che',
            'da', 'gei', 'mai', 'yong', 'fang', 'kai', 'guan', 'jin', 'chu', 'shang',
            'xia', 'da', 'xiao', 'duo', 'shao', 'chang', 'duan', 'gao', 'di', 'yuan',
            'jin', 'kuai', 'man', 'xin', 'jiu', 'nian qing', 'hao', 'huai', 'mei li',
            'piao liang', 'nan kan', 'shuai', 'pang', 'shou', 'qiang', 'ruo', 'le',
            'nan guo', 'gao xing', 'kai xin', 'shang xin', 'sheng qi', 'hai pa',
            'jin zhang', 'fang song', 'mang', 'xian', 'e', 'ke', 'xue xiao', 'jia',
            'gong zuo', 'peng you', 'jia ting', 'fu mu', 'er zi', 'nv er', 'xiong di',
            'jie mei', 'xian sheng', 'nv shi', 'xiao jie', 'tong xue', 'lao shi',
            'yi sheng', 'huo che', 'fei ji', 'gong gong qi che', 'di tie', 'zi xing che',
            'shou ji', 'dian nao', 'dian shi', 'deng', 'shui', 'huo', 'kong qi',
            'tian qi', 'tai yang', 'yue liang', 'xing xing', 'yun', 'yu', 'xue',
            'feng', 'shan', 'hai', 'he', 'hua', 'cao', 'shu', 'sen lin', 'dong wu',
            'gou', 'mao', 'niao', 'yu', 'ma yi', 'hu die', 'ji qi', 'ke ji',
            'wen hua', 'li shi', 'di li', 'ke xue', 'yi shu', 'yin yue', 'ti yu',
            'jian kang', 'shen ti', 'yun dong', 'you xi', 'dian ying', 'gu shi',
            'jian dan', 'fu za', 'te bie', 'pu tong', 'an quan', 'wei xian'
        ]
    }
};
